app:
  appEnv: "dev"
  connectionString: "postgres://root:secret@db:5432/gs_chatbot?sslmode=disable"

twitch:
  clientId: "123"
  clientSecret: "123"
  callbackUrl: "localhost:3000"

bot:
  username: "gguuse"
  accessToken: "oauth:123"
  # refreshToken: ""